KinControlNode:
  ros__parameters:
    auto_enabled: true
    mute: false
    min_lookahead: 10.0
    max_lookahead: 50.0
    lookahead_speed_ratio: 0.6
    proportional_gain: 0.2    
    derivative_gain: 0.0    
    max_steer_angle: 15.0
    vehicle:
      wheelbase: 2.9718
      cg_to_front: 1.723644
      cg_to_rear: 1.248156
      tire_stiffness_front: 100000.0
      tire_stiffness_rear: 100000.0
      mass: 720.0
      inertia: 1000.0
      
    max_lat_error: 2.5
    max_lookagead_error: 2.5
    
    curv_to_velocity_constant: 0.5 # converts path curvature to max velocity 
