LongControlNode:
  ros__parameters:
    auto_enabled: true
    mute: false
    override_absent_joystick: true 
    max_desired_velocity: 100.0
    time_step: 0.01
    throttle:
      proportional_gain: 4.0 
      integral_gain: 0.0 
      derivative_gain: 0.0
      max_integrator_error: 50.0
      cmd_max: 100.0
      cmd_min: 0.0
      reset_integral_below_this_cmd: 15.0
    brake:
      proportional_gain: 200.0 
      integral_gain: 0.005 
      derivative_gain: 0.0
      max_integrator_error: 10.0
      cmd_max: 1400.0 
      cmd_min: 0.0
      reset_integral_below_this_cmd: 100.0
      vel_error_deadband: 0.1
    gear:
      shift_up: 6000.0
      shift_down: 3000.0
      shift_time_ms: 1000


